<?php

namespace FHJ\ConsoleCommands;

use Symfony\Component\Console\Command\Command;
use Symfony\Component\Console\Input\InputInterface;
use Symfony\Component\Console\Output\OutputInterface;
use Symfony\Component\Console\Input\InputArgument;
use Symfony\Component\Console\Input\InputOption;

/**
 * UpdateSvnDataCommand
 * @package FHJ\ConsoleCommands
 */
class UpdateSvnDataCommand extends Command {

	protected function configure()
	{
		parent::configure(); // TODO: Change the autogenerated stub
	}

	protected function execute(InputInterface $input, OutputInterface $output)
	{
		parent::execute($input, $output); // TODO: Change the autogenerated stub
	}

} 