<?php

namespace FHJ\Framework;

use Symfony\Component\Form\AbstractType;
use Symfony\Component\Form\FormBuilderInterface;
use Symfony\Component\Form\FormInterface;
use Symfony\Component\Form\FormView;
use Symfony\Component\OptionsResolver\OptionsResolverInterface;

/**
 * SimpleLinkButtonType
 * @package FHJ\Framework
 */
class SimpleLinkButtonType extends AbstractType {

	public function setDefaultOptions(OptionsResolverInterface $resolver) {
		$resolver->setDefaults(array(
			'choices' => array(
				'm' => 'Male',
				'f' => 'Female',
			)
		));
	}

	public function getParent() {
		return 'button';
	}

	public function buildForm(FormBuilderInterface $builder, array $options) {
		parent::buildForm($builder, $options); // TODO: Change the autogenerated stub
	}

	public function buildView(FormView $view, FormInterface $form, array $options) {
		parent::buildView($view, $form, $options); // TODO: Change the autogenerated stub
	}

	public function finishView(FormView $view, FormInterface $form, array $options) {
		parent::finishView($view, $form, $options); // TODO: Change the autogenerated stub
	}


	/**
	 * Returns the name of this type.
	 * @return string The name of this type
	 */
	public function getName()
	{
		return 'link';
	}
}